[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.environment]
NODE_VERSION = "18"
PHP_VERSION = "8.2"
COMPOSER_VERSION = "2"

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public"

[deploy]
preDeployCommand = "php artisan migrate --force && php artisan db:seed --class=RoleAndPermissionSeeder --force && php artisan db:seed --class=RoleUser --force"

[[services]]
type = "web"
numReplicas = 1
